// <auto-generated />
namespace ProductManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updateeurromessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateeurromessage));
        
        string IMigrationMetadata.Id
        {
            get { return "202001100444409_update eurro message"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
